# Generated by Django 5.1.7 on 2025-03-10 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='client',
        ),
    ]
